version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "5002:5002"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/travel-recommendations
      - PORT=5002
      - NODE_ENV=development
      - AMADEUS_API_KEY=0QZQWiPJSrGgNgAAG3YPtOjeybdw8wQm
      - AMADEUS_API_SECRET=aqjF5p6A3RhkAd4J
      - AMADEUS_BASE_URL=https://test.api.amadeus.com/v1
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - app-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    depends_on:
      - server
    environment:
      - REACT_APP_API_URL=http://localhost:5002/api
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data: